version: "2.1"

services:
  postgres:
    hostname: postgres-db
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  django-app:
    build:
      context: ./djangoProject
    container_name: app-hw3
    depends_on:
      - postgres
    volumes:
      - ./djangoProject:/app
    ports:
      - "8000:8000"
    entrypoint: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    depends_on:
      - django-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80